fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "%env(MAILER_SENDER)%"
        sender_name: "%env(MAILER_USER)%"
    profile:
        form:
            type: App\Form\EditType
    registration:
        form:
            type: App\Form\RegistrationType
